
sigma^2: 100%|®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä| 5/5 [00:03<00:00,  1.64it/s]
ho: 100%|®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä| 50/50 [01:55<00:00,  2.32s/it]
leverages 1:   0%|          | 0/5 [01:20<?, ?it/s]
Breaking loop - threshold for max Pii is 0.999, with 50 draw(s) per batch and a maximum of 5 batch(es) being drawn. There is/are 72 observation(s) with Pii above this threshold. This/these will be recomputed analytically. It took 1 batch(es) to get below the threshold of 100 bad observation(s).
leverages 2: 100%|®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä| 72/72 [00:16<00:00,  4.33it/s]
C:\Users\mazhihao\Downloads\download\Anaconda\lib\site-packages\pytwoway\fe.py:1419: RuntimeWarning: divide by zero encountered in true_divide
  Sii_s = (self.Y[~worker_m] - Y_bar) * (self.E[~worker_m] / (1 - Pii_s))
he:   0%|          | 0/50 [00:00<?, ?it/s]C:\Users\mazhihao\Downloads\download\Anaconda\lib\site-packages\pytwoway\fe.py:1156: RuntimeWarning: invalid value encountered in subtract
  psi_out = self.ml.solve(psi - self.J.T * (self.Dp * (self.W * (self.Dwinv * alpha))), tol=1e-10)
he: 100%|®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä®Ä| 50/50 [02:48<00:00,  3.37s/it]
